### ISSUE TITLE
Serve and upload not working on non default theme

### ISSUE THREAD

**Issue by gcjbr** [Edools/edools-theme-cli#2]
It returns this error
```
edt serve
/usr/local/lib/node_modules/edools-theme-cli/bin/config.js:122
      cb(origin.refs.fetch.indexOf('/elegance') > -1);
               ^

TypeError: Cannot read property 'refs' of undefined
    at git.getRemotes (/usr/local/lib/node_modules/edools-theme-cli/bin/config.js:122:16)
    at /usr/local/lib/node_modules/edools-theme-cli/node_modules/simple-git/src/git.js:721:18
    at Git.<anonymous> (/usr/local/lib/node_modules/edools-theme-cli/node_modules/simple-git/src/git.js:761:18)
    at Git.<anonymous> (/usr/local/lib/node_modules/edools-theme-cli/node_modules/simple-git/src/git.js:1284:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
```

I can get it to work if I just isDefaultTheme, on config.js return false, but I'm not sure how it would affect someone trying to edit the default theme, though.

**Comment by sudomf** [comment]
Hi @souljacker, do you have you a `.git` folder inside the theme's folder?

**Comment by sudomf** [comment]
@souljacker A bug was detected and solved, please update the CLI running `npm i -g edools-theme-cli`.
