### ISSUE TITLE
Problema para iniciar novo tema

### ISSUE THREAD

**Issue by samuellealb** [Edools/edools-theme-cli#7]
Consegui compilar o edools-theme-cli normalmente tanto com o node 6 quanto com o 7 (sempre na sub-versão mais recente de cada um).

No entanto quanto tento iniciar um novo tema, ocorre o erro abaixo:

```
/home/popos/.nvm/versions/node/v7.10.1/lib/node_modules/edools-theme-cli/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/popos/.nvm/versions/node/v7.10.1/lib/node_modules/edools-theme-cli/node_modules/browser-sync/dist/public/stream.js:3:18)
```

**Obs**: Estou trabalhando com um ambiente **Linux (Pop!_OS 20.10) / AMD64**

**Comment by samuellealb** [comment]
Resolvido usando o node 8. Talvez fosse o caso de atualizar a documentação.
